name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-knip-build:
    name: Lint, Knip, and Build
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Knip analysis
        run: npx --yes knip

      - name: Build
        run: npm run build
